# Generated by Django 4.0.6 on 2023-04-23 05:37

from django.db import migrations, models
import my_store_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryproduct",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="символьный код"),
        ),
        migrations.AlterField(
            model_name="categoryproduct",
            name="image",
            field=models.FileField(null=True, upload_to="my_store_app/static/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_picture",
            field=models.ImageField(
                null=True, upload_to=my_store_app.models.create_image_path_for_product
            ),
        ),
    ]
