# Generated by Django 4.0.6 on 2023-04-23 06:10

from django.db import migrations, models
import my_store_app.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "my_store_app",
            "0002_categoryproduct_slug_alter_categoryproduct_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="categoryproduct",
            name="image",
            field=models.FileField(
                null=True, upload_to=my_store_app.models.create_image_path_for_category
            ),
        ),
    ]
