# Generated by Django 4.0.6 on 2023-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0003_product_slug_alter_categoryproduct_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited_edition",
            field=models.BooleanField(default=False, verbose_name="ограниченный тираж"),
        ),
    ]
