# Generated by Django 4.0.6 on 2023-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0005_categoryproduct_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryproduct",
            name="tags",
        ),
        migrations.AddField(
            model_name="categoryproduct",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="tags_in_category",
                to="my_store_app.tagsfile",
            ),
        ),
    ]
