# Generated by Django 4.0.6 on 2023-04-23 19:07

from django.db import migrations, models
import my_store_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0008_alter_limitedoffer_options_limitedoffer_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=my_store_app.models.create_image_path_for_product,
            ),
        ),
    ]
