# Generated by Django 4.0.6 on 2023-04-23 19:52

from django.db import migrations, models
import django.db.models.deletion
import my_store_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0009_alter_product_product_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=my_store_app.models.create_image_path_for_product_gallery
                    ),
                ),
                (
                    "product_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="my_store_app.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="gallery",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="my_store_app.productimage"
            ),
        ),
    ]
