# Generated by Django 4.0.6 on 2023-04-24 05:38

from django.db import migrations, models
import my_store_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0012_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=my_store_app.models.create_image_path_for_product_gallery
            ),
        ),
    ]
