# Generated by Django 4.0.6 on 2023-04-24 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0013_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitedoffer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
    ]
