# Generated by Django 4.0.6 on 2023-04-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0014_limitedoffer_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="big_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="большой текст для карточки товара"
            ),
        ),
    ]
