# Generated by Django 4.0.6 on 2023-04-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0016_profile_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="basket_items_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
