# Generated by Django 4.0.6 on 2023-05-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0021_orderhistory_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderhistory",
            name="order",
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="order",
            field=models.ManyToManyField(
                to="my_store_app.order", verbose_name="заказы"
            ),
        ),
    ]
