# Generated by Django 4.0.6 on 2023-05-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0022_remove_orderhistory_order_orderhistory_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="количество")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата изменения"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_store_app.product",
                        verbose_name="товар",
                    ),
                ),
            ],
        ),
    ]
