# Generated by Django 4.0.6 on 2023-05-05 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0023_productcounthistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductCountHistory",
        ),
    ]
