# Generated by Django 4.0.6 on 2023-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0026_alter_orderedproduct_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderedproduct",
            options={
                "verbose_name": "Заказанный товар",
                "verbose_name_plural": "Заказанные товары",
            },
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="products",
            field=models.ManyToManyField(
                related_name="products_with_quantity",
                through="my_store_app.OrderedProduct",
                to="my_store_app.product",
                verbose_name="товары",
            ),
        ),
    ]
