# Generated by Django 4.0.6 on 2023-05-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0027_alter_orderedproduct_options_orderhistory_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="basket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="my_store_app.basket",
            ),
        ),
    ]
