# Generated by Django 4.0.6 on 2023-05-06 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0028_profile_basket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="basket_items_count",
        ),
    ]
