# Generated by Django 4.0.6 on 2023-05-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0029_remove_profile_basket_items_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                default="Не указано",
                max_length=30,
                null=True,
                verbose_name="номер телефона",
            ),
        ),
    ]
