# Generated by Django 4.0.6 on 2023-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0030_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email пользователя"
            ),
        ),
    ]
