# Generated by Django 4.0.6 on 2023-05-06 10:52

from django.db import migrations, models
import my_store_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0031_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="catalog/files/ava-default.png",
                null=True,
                upload_to="catalog/files/",
                validators=[my_store_app.models.Profile.validate_image],
            ),
        ),
    ]
