# Generated by Django 4.0.6 on 2023-05-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_store_app", "0032_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="Подтвержден"),
        ),
    ]
